// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxM0YMFYRJbyVt4O9ZD7s2fATFf1UiHA',
    appId: '1:175650031073:web:38a26ad9f0aa738423fea0',
    messagingSenderId: '175650031073',
    projectId: 'psicologia-9d32a',
    authDomain: 'psicologia-9d32a.firebaseapp.com',
    storageBucket: 'psicologia-9d32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFKm7OU8AgWzyOMW44vPtSulj26v64-8',
    appId: '1:175650031073:android:a43947a65e8f76b123fea0',
    messagingSenderId: '175650031073',
    projectId: 'psicologia-9d32a',
    storageBucket: 'psicologia-9d32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwf1mp5TB-GmA-G-AahgvD1hNMYaZqj4',
    appId: '1:175650031073:ios:35f8b0056b5460d123fea0',
    messagingSenderId: '175650031073',
    projectId: 'psicologia-9d32a',
    storageBucket: 'psicologia-9d32a.appspot.com',
    iosClientId: '175650031073-pa341r2dnec37ajspa57aebe8kqfq0hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwf1mp5TB-GmA-G-AahgvD1hNMYaZqj4',
    appId: '1:175650031073:ios:18333674db2f5d7923fea0',
    messagingSenderId: '175650031073',
    projectId: 'psicologia-9d32a',
    storageBucket: 'psicologia-9d32a.appspot.com',
    iosClientId: '175650031073-ss9t9j5qg562s2946sre0hvjde1ag5rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
